---
title: "My first post"
date: 2018-11-18
---

title: Githhub education
author: GitHub User Natalia
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Niice site for Github education

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
